### ISSUE TITLE
`sst init` errors in fresh directory

### ISSUE THREAD

**Issue by ethan-stone-gas** [sst/ion#45]
---

Discussion on Discord [https://discord.com/channels/983865673656705025/1177071497974648952/1220196175165132881](https://discord.com/channels/983865673656705025/1177071497974648952/1220196175165132881).

Trying to initialize an sst project in a completely new directory. Did the following.

* `mkdir sst-ion-test`
* `cd sst-ion-test`
* `pnpm init`
* `sst init`

`sst init` when run with verbose just gives the following.

![image](https://uploads.linear.app/a959060b-9262-4398-9650-16bf10f1450e/cd51c878-e861-4d45-9bf6-c334367e37cf/04ec2446-7394-4c97-8e71-18668e081b84?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E5NTkwNjBiLTkyNjItNDM5OC05NjUwLTE2YmYxMGYxNDUwZS9jZDUxYzg3OC1lODYxLTRkNDUtOWJmNi1jMzM0MzY3ZTM3Y2YvMDRlYzI0NDYtNzM5NC00Yzk3LThlNzEtMTg2NjhlMDgxYjg0IiwiaWF0IjoxNzExNTkxMjM0LCJleHAiOjE3MTE2Nzc2MzR9.96MNoSbtQmbiSf1wvaulzcf8WTFUtmH70GLAvL7-\_3s)

<sub>From [SyncLinear.com](https://synclinear.com) | [ION-216](https://linear.app/sst-dev/issue/ION-216/sst-init-errors-in-fresh-directory)</sub>

**Comment by ethan-stone-gas** [comment]
Was able to resolve this thanks to help from this comment. https://discord.com/channels/983865673656705025/1177071497974648952/1220363650997686293

By specifying the `AWS_PROFILE="my-profile" sst init` it worked. Will leave this issue open now in case you all want to investigate further and confirm that's the cause.

**Comment by thdxr** [comment]
can you still create this issue on 0.0.189 of sst?

**Comment by ethan-stone-gas** [comment]
I have not been able to reproduce it, unfortunately. I logged out of all sso sessions on my machine and now even `sst init` without specifying `AWS_PROFILE` seems to be working now as well.

**Comment by stamatim** [comment]
I am also encountering this.

### Steps

```txt
npx create-next-app@latest ion-test --typescript --tailwind --eslint
cd ion-test
AWS_PROFILE="personal" sst init
```

### Output

```sh
▲ (0xMBP14.lan) Sandbox AWS_PROFILE="personal" sst init

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║
   ╚════██║╚════██║   ██║
   ███████║███████║   ██║
   ╚══════╝╚══════╝   ╚═╝

>  Next.js detected. This will...
   - create an sst.config.ts
   - modify the tsconfig.json
   - add the sst sdk to package.json

✓  Template: nextjs

✓  Using: aws

×  Unexpected error occurred. Please check the logs for more details.
```

**Comment by stamatim** [comment]
Something else I noticed as well is that after running the `sst init` command, the following files were modified while the command was running and the contents of each file are empty:

1. `.gitignore`
2. `package-lock.json`
3. `package.json`
4. `sst-env.d.ts`
5. `tsconfig.json`

**Comment by oieduardorabelo** [comment]
i don't have aws profile available globally, i use [aws-vault](https://github.com/99designs/aws-vault)

and `sst init` , in a new directory (empty folder), doesn't work, it exits with `?1`:

![CleanShot 2024-03-23 at 01 53 57](https://github.com/sst/ion/assets/829902/8cd378dd-c061-4fd9-ac77-59fb9752d55a)

**Comment by thdxr** [comment]
for those of you seeing an error when `installing providers` i pushed verison 190 should potentially have better info in `--verbose` mode if you can share that

**Comment by thdxr** [comment]
> i don't have aws profile available globally, i use [aws-vault](https://github.com/99designs/aws-vault)
> 
> and `sst init` , in a new directory (empty folder), doesn't work, it exits with `?1`:
> 
> ![CleanShot 2024-03-23 at 01 53 57](https://private-user-images.githubusercontent.com/829902/316014753-8cd378dd-c061-4fd9-ac77-59fb9752d55a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTk1MDMsIm5iZiI6MTcxMTExOTIwMywicGF0aCI6Ii84Mjk5MDIvMzE2MDE0NzUzLThjZDM3OGRkLWMwNjEtNGZkOS1hYzc3LTU5ZmI5NzUyZDU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNDUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTZhM2JhZTFjZTMyYzU1MTk0NjM1Y2Y2ZWUyZjBhNTM5NGQ3NDA4NzRkNDAyY2MzODVmZGI1MzkwOTRhNTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MIDVM9wBC-0OJ_xxnOv7HklhMwAc0aX9yHo_UAqVHdc)

i'm not sure about this - `sst init` should not require any aws information at all, can you verify you're on the latest version and show me the output from `--verbose`

**Comment by oieduardorabelo** [comment]
> > i don't have aws profile available globally, i use [aws-vault](https://github.com/99designs/aws-vault)
> > and `sst init` , in a new directory (empty folder), doesn't work, it exits with `?1`:
> > ![CleanShot 2024-03-23 at 01 53 57](https://private-user-images.githubusercontent.com/829902/316014753-8cd378dd-c061-4fd9-ac77-59fb9752d55a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjE2OTksIm5iZiI6MTcxMTEyMTM5OSwicGF0aCI6Ii84Mjk5MDIvMzE2MDE0NzUzLThjZDM3OGRkLWMwNjEtNGZkOS1hYzc3LTU5ZmI5NzUyZDU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDFjM2E0OGQ5ZThiOGEzMjQ0MjcxMmQzNWY1Y2ZkNDkzNDcwYTIyNDBjNmY4N2JhZWVjYzE0ZDY3NWFiODhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H8RodGxj_LVivJdREJC5nucVwYHt-1u-kDFdDHftCfY)
> 
> i'm not sure about this - `sst init` should not require any aws information at all, can you verify you're on the latest version and show me the output from `--verbose`

i executed `curl -fsSL https://ion.sst.dev/install | bash` again, using version `0.0.191`

![CleanShot 2024-03-23 at 04 41 27](https://github.com/sst/ion/assets/829902/da602557-b863-48eb-b289-c8ddd332bb6c)

working as expected, thank you! 🚀

**Comment by stamatim** [comment]
@thdxr I am still having some issues, here is what I did:

## Steps

1. Install `sst` - `curl -fsSL https://ion.sst.dev/install | bash` (`v0.0.193`)
2. Create Next.js app - `npx create-next-app@latest ion-nextjs --typescript --tailwind --eslint`
3. `cd ion-nextjs`
4. Init `sst` - `AWS_PROFILE="personal" sst init --verbose`

## Output

```sh
▲ (0xMBP14.lan) ion-nextjs [main] AWS_PROFILE="personal" sst init --verbose
time=2024-03-22T11:31:37.883-05:00 level=INFO msg="checking for bun" path="/Users/stamati/Library/Application Support/sst/bin/bun"

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║   
   ╚════██║╚════██║   ██║   
   ███████║███████║   ██║   
   ╚══════╝╚══════╝   ╚═╝   

>  Next.js detected. This will...
   - create an sst.config.ts
   - modify the tsconfig.json
   - add the sst sdk to package.json

✓  Template: nextjs

✓  Using: aws

time=2024-03-22T11:31:39.918-05:00 level=INFO msg="creating project" name=ion-nextjs
time=2024-03-22T11:31:39.919-05:00 level=INFO msg="copying template" path=templates/nextjs/files/sst-env.d.ts
time=2024-03-22T11:31:39.919-05:00 level=INFO msg="copying template" path=templates/nextjs/files/sst.config.ts
time=2024-03-22T11:31:39.920-05:00 level=INFO msg=patching file=tsconfig.json
time=2024-03-22T11:31:39.924-05:00 level=INFO msg=patching file=package.json
time=2024-03-22T11:31:39.927-05:00 level=INFO msg="handling .gitignore" section="# open-next"
⠋  Installing providers...time=2024-03-22T11:31:39.929-05:00 level=INFO msg="esbuild building"
time=2024-03-22T11:31:39.941-05:00 level=INFO msg="esbuild built" outfile=/Users/stamati/Developer/Sandbox/ion-nextjs/.sst/eval/eval-1711125099928.mjs
time=2024-03-22T11:31:39.942-05:00 level=INFO msg="evaluating config"
time=2024-03-22T11:31:39.988-05:00 level=INFO msg="config evaluated"
time=2024-03-22T11:31:39.988-05:00 level=INFO msg="installing platform"
⠙  Installing providers...time=2024-03-22T11:31:40.046-05:00 level=INFO msg="installing deps"
time=2024-03-22T11:31:40.046-05:00 level=INFO msg="writing package.json"
time=2024-03-22T11:31:40.046-05:00 level=INFO msg="adding dependency" name=aws
time=2024-03-22T11:31:40.047-05:00 level=INFO msg="fetching deps"
⠋  Installing providers...time=2024-03-22T11:31:41.021-05:00 level=ERROR msg="exited with error" err="failed to run bun install bun install v1.0.35 (940448d6)\nnode:internal/child_process:1124\n    result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);\n                   ^\n\n<ref *1> Error: spawnSync /Users/stamati/Developer/Sandbox/ion-nextjs/.sst/platform/node_modules/esbuild/bin/esbuild EACCES\n    at Object.spawnSync (node:internal/child_process:1124:20)\n    at spawnSync (node:child_process:876:24)\n    at Object.execFileSync (node:child_process:919:15)\n    at validateBinaryVersion (/Users/stamati/Developer/Sandbox/ion-nextjs/.sst/platform/node_modules/esbuild/install.js:99:28)\n    at /Users/stamati/Developer/Sandbox/ion-nextjs/.sst/platform/node_modules/esbuild/install.js:286:5 {\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'spawnSync /Users/stamati/Developer/Sandbox/ion-nextjs/.sst/platform/node_modules/esbuild/bin/esbuild',\n  path: '/Users/stamati/Developer/Sandbox/ion-nextjs/.sst/platform/node_modules/esbuild/bin/esbuild',\n  spawnargs: [ '--version' ],\n  error: [Circular *1],\n  status: null,\n  signal: null,\n  output: null,\n  pid: 0,\n  stdout: null,\n  stderr: null\n}\n\nNode.js v21.5.0\n\nerror: postinstall script from \"esbuild\" exited with 1\n"
×  Unexpected error occurred. Please check the logs or run with --verbose for more details.
```

**Comment by jayair** [comment]
Thanks for tracking it down. @thdxr take a look?

**Comment by imdkbj** [comment]
Hey @thdxr
providers credentials are not being utilised in sst dev too. Have to explicitly pass
AWS_PROFILE="personal" sst dev

Tried Below in old and new repo but no luck

```js
 providers: {
        aws: {
          region: "ap-south-1",
          accessKey: "A",
          secretKey: "B",
        },
      }
```

or
profile: "personal"

It is taking default profile only.

**Comment by thdxr** [comment]
we added a `NO_BUN` environment variable for now, will follow up on the bun issue ty

**Comment by gyenabubakar** [comment]
I'm facing this issue in a SvelteKit app. Using the `curl / bash` installation and `npx sst@ion`:

```
time=2024-07-28T10:31:47.906Z level=INFO msg="checking for pulumi" path="/Users/gyen/Library/Application Support/sst/bin/pulumi"
time=2024-07-28T10:31:48.185Z level=INFO msg="checking for bun" path="/Users/gyen/Library/Application Support/sst/bin/bun"

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║
   ╚════██║╚════██║   ██║
   ███████║███████║   ██║
   ╚══════╝╚══════╝   ╚═╝

>  SvelteKit detected. This will...
   - create an sst.config.ts
   - add sst to package.json

✓  Template: svelte-kit

time=2024-07-28T10:31:51.957Z level=INFO msg="creating project" name=the-sveltekit-app
time=2024-07-28T10:31:51.959Z level=ERROR msg="exited with error" err="invalid character ']' looking for beginning of value"
✕  Unexpected error occurred. Please check the logs or run with --verbose for more details.
```

**Comment by behboud** [comment]
@gyenabubakar I had similar issue and resolved it by removing old sst bootstrap including parameter store entries.

**Comment by gyenabubakar** [comment]
> @gyenabubakar I had similar issue and resolved it by removing old sst bootstrap including parameter store entries.

@behboud I did not understand what you said 😅. What am I removing, and how?

**Comment by jayair** [comment]
@gyenabubakar Have you used SST on this AWS account before? I think @behboud means he cleared the state: https://ion.sst.dev/docs/state/
