### ISSUE TITLE
Multiple cookie headers are not supported for Remix platform

### ISSUE THREAD

**Issue by alfredsgenkins** [sst/ion#674]
Hey!

I am not 100% sure if that's an issue with SST. All I know at this point, is that I have a Remix package, implementing the following logic to set multiple cookies: https://github.com/remix-run/remix/issues/231#issuecomment-2227992952.

On local (with remix-serve) it works well, it outputs the multiple headers in response:
![image](https://github.com/user-attachments/assets/90a5874c-22b6-4c9b-93ec-0ee19e956940)

In production, or deployed, only first cookie is set:
![image](https://github.com/user-attachments/assets/8e4870e9-1c3b-46a5-a7d4-17260907ccd7)

I have found some information on special format, that lambdas should follow to declare cookies: https://stackoverflow.com/a/68994753.

I will continue my investigation.

**Comment by luke-rucker** [comment]
fixed with #702. it's in v0.0.539

**Comment by alfredsgenkins** [comment]
After upgrading to this version (to v.0.0.540) all my functions now fail with following error:

```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "response.headers.getSetCookie is not a function",
    "stack": [
        "TypeError: response.headers.getSetCookie is not a function",
        "    at Runtime.handler (file:///var/task/build/server.mjs:113737:33)",
        "    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)"
    ]
}
```

Am I missing something?

**Comment by luke-rucker** [comment]
Ah, sorry about that. I'll open another PR that doesn't require `getSetCookie`

**Comment by alfredsgenkins** [comment]
I have removed the above mentioned `installGlobals()` command. However, I am still getting the same single cookie result (last set-cookie header) as before:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/610869ff-848d-49b7-9603-f82ebf8ef29e">

While the expected result from the code bellow is two set-cookie headers.

```js
class {
  async getLogoutHeaders() {
    const headers = new Headers();

    headers.append(
      "Set-Cookie",
      await idTokenCookie.serialize("", { maxAge: 0 }),
    );

    headers.append(
      "Set-Cookie",
      await refreshTokenCookie.serialize("", { maxAge: 0 }),
    );

    return headers;
  }
}
```

<img width="232" alt="image" src="https://github.com/user-attachments/assets/35e68ab3-0d7b-4f24-8bf2-247d8328a311">

**Comment by luke-rucker** [comment]
just opened a pr that should fix this, polyfills or not: #709.

as far as your issues with different behavior locally vs in ci, the cli recently started being packaged along with the npm package. so you can now get rid of your global installation, and work with the cli through `pnpm sst`. it's more to type but more convenient imo as the cli will always match the sdk version, preventing any headaches like you experienced

**Comment by luke-rucker** [comment]
the fix of the fix is in v0.0.545 :)

**Comment by alfredsgenkins** [comment]
It did solve the issue! However, my headers are sent +1 times. I think `set-cookie` must be removed from headers, once converted to `cookies`. For example, I tried sending `id_token` and `refresh_token` cookies.

Instead, I got these:
1. <img width="301" alt="image" src="https://github.com/user-attachments/assets/b9ef8bbf-f551-4e32-a4ae-4f85368405a8">
2. <img width="317" alt="image" src="https://github.com/user-attachments/assets/21aff76d-7765-4e7d-9a32-923199779748">
3. <img width="290" alt="image" src="https://github.com/user-attachments/assets/36aaa875-5c9d-42fd-bcbb-2972491efc28">

There should be just 2 of them, not 3. I do not think the issue is critical anymore, yet I think it would be best if we address this inconsistency too.

**Comment by jayair** [comment]
Would appreciate a PR1
